// This file is autogenerated. Changes will be overwritten.
#include "Y3ATEJKCV3/moc_dynamicwindow.cpp"
#include "LATUH32JQ6/moc_staticwidget.cpp"
#include "U7HF7WGTV7/moc_draw.cpp"
#include "EWIEGA46WW/moc_mainwindow.cpp"
#include "3HT3KXAPXP/moc_drawColorMenu.cpp"
#include "HWGEFW6YQ7/moc_colorwidget.cpp"
#include "HWGEFW6YQ7/moc_selectColorWindowPredef.cpp"
